"""Add is_blocked column to User model

Revision ID: 813f7730d5c5
Revises: 
Create Date: 2025-05-29 13:58:16.105139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813f7730d5c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
